services:
  api:
    build: 
          context: .. 
          dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://localstack:4566
  mlflow:
    build: 
          context: .. 
          dockerfile: docker/Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ../mlflow.db:/src/mlflow.db
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-1
      - MLFLOW_S3_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
  prefect:
    build: 
          context: .. 
          dockerfile: docker/Dockerfile.prefect
    ports:
      - "4200:4200"
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3